### ISSUE TITLE
Make sorting for paintings - based on all the rows we have included in our db

### ISSUE THREAD

**Issue by henrynavntoft** [henrynavntoft/full-stack-exam#21]
Color, year, artist, etc. So its cool and nice to sort and filter.

**Comment by federico-barbieri** [comment]
We have 3 filters: by search (look for a title), by artist and by period (in centuries). 

The artist options in the select HTML can be expanded based on how many artworks we fetch for production. I chose those who have the most artworks in our current batch.

The period goes from the 1500's to the 1700's. Our current batch doesn't have any from the 1700's so we need to expand it.

I'll close this one for now but as I said, there can be 50 more filters.
